import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "../lib/supabase";
import V2Page, { V2EmptyState } from "../components/v2rail/V2Page";
import QueueRow from "../components/v2rail/QueueRow";
import BacklogTicketDrawer from "./backlogv2/BacklogTicketDrawer";
import { ageShort } from "./contentv2/utils";
import "./backlogv2/backlogv2.css";

// Staff triage queue for the backlog lane: the bugs and ideas academies send
// through the support icon in the V2 client portal.
//
// WHY THIS PAGE EXISTS: every other lane had a staff page and this one did not.
// `fix` and `feature_idea` route to backlog BY DESIGN so they get triaged before
// they hit a team's queue, but with nothing rendering the lane, a client bug
// report landed in a table no screen displayed. A real one (We BUILD, a wrong
// clinic address on a live page) sat unseen until someone went looking in SQL.
// The Feedback page looks like it should cover this and does not: it reads
// portal_feedback, the older widget, not v2_tickets.
//
// SCOPE: the support icon is V2-only, so every ticket here comes from a V2
// academy. That is why this is its own page rather than a merge into Feedback,
// which also carries V1, V1.5, signup and staff-portal submissions.
//
// Same data patterns as ContentV2View / MarketingV2View: reads through
// supabase-js (staff RLS = all) with a realtime subscription, every mutation
// through /api/v2-tickets.

const BACKLOG_ROLE = "backlog";

const TABS = [
  { id: "new", label: "New", statuses: ["new"] },
  { id: "in_progress", label: "In progress", statuses: ["in_progress", "waiting_client"] },
  { id: "done", label: "Done", statuses: ["resolved", "closed"] },
];
const OPEN_STATUSES = ["new", "in_progress", "waiting_client"];

// The only two types that route here (api/v2-tickets.js TYPE_ROLE).
const KINDS = [
  { id: "all", label: "All" },
  { id: "fix", label: "Bugs" },
  { id: "feature_idea", label: "Ideas" },
];

const KIND_LABEL = { fix: "Bug", feature_idea: "Idea" };

// The client typed into a single free-text box, so the description is the
// ticket. The title is auto-generated by truncating that text at 60 characters,
// which is why the row prefers the full description for its sub-line.
function subLine(t) {
  const parts = [KIND_LABEL[t.type] || "Request"];
  const desc = (t.intake?.description || "").replace(/\s+/g, " ").trim();
  if (desc) parts.push(desc.length > 90 ? `${desc.slice(0, 90)}...` : desc);
  return parts.join(" · ");
}

export default function BacklogV2View({ dark, session }) {
  const [tickets, setTickets] = useState([]);
  const [clientsMap, setClientsMap] = useState({});
  const [staffList, setStaffList] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [activeTab, setActiveTab] = useState("new");
  const [kind, setKind] = useState("all");
  const [openId, setOpenId] = useState(null);
  const didInit = useRef(false);

  const staffMap = useMemo(() => {
    const m = {};
    for (const s of staffList) m[s.id] = s.name;
    return m;
  }, [staffList]);

  // ── Reads (supabase-js) ──
  async function loadQueue() {
    const { data, error: err } = await supabase
      .from("v2_tickets")
      .select("*")
      .eq("assignee_role", BACKLOG_ROLE)
      .order("updated_at", { ascending: false })
      .limit(200);
    if (err) { setError(err.message); setLoading(false); return; }
    setError("");
    setTickets(data || []);
    setLoading(false);
  }

  async function loadMaps() {
    const [{ data: clients }, { data: staff }] = await Promise.all([
      supabase.from("clients").select("id,business_name").order("business_name"),
      supabase.from("staff").select("id,name,role").order("name"),
    ]);
    const cm = {};
    for (const c of clients || []) cm[c.id] = c.business_name;
    setClientsMap(cm);
    setStaffList(staff || []);
  }

  useEffect(() => {
    if (didInit.current) return;
    didInit.current = true;
    loadMaps();
    loadQueue();
    const ch = supabase
      .channel("backlogv2-queue")
      .on("postgres_changes", { event: "*", schema: "public", table: "v2_tickets" }, () => loadQueue())
      .on("postgres_changes", { event: "*", schema: "public", table: "v2_ticket_messages" }, () => loadQueue())
      .subscribe();
    return () => { supabase.removeChannel(ch); };
  }, []);

  // Triage MOVES a ticket out of this lane, so the drawer must close when the
  // open ticket leaves rather than hang on a row that is no longer here.
  useEffect(() => {
    if (openId && !loading && !tickets.some((t) => t.id === openId)) setOpenId(null);
  }, [tickets, openId, loading]);

  const counts = useMemo(() => {
    const c = {};
    for (const tab of TABS) c[tab.id] = 0;
    for (const t of tickets) {
      for (const tab of TABS) if (tab.statuses.includes(t.status)) c[tab.id]++;
    }
    return c;
  }, [tickets]);

  const openCount = useMemo(
    () => tickets.filter((t) => OPEN_STATUSES.includes(t.status)).length,
    [tickets],
  );

  const activeStatuses = TABS.find((t) => t.id === activeTab)?.statuses || [];
  const visible = tickets.filter(
    (t) => activeStatuses.includes(t.status) && (kind === "all" || t.type === kind),
  );
  const openTicket = tickets.find((t) => t.id === openId) || null;

  return (
    <V2Page
      dark={dark}
      title="Backlog"
      sub="Bugs and ideas from the V2 support icon. Triage each one, then send it to the team that owns it."
    >
      <section className="v2r-queue-card">
        <div className="v2r-queue-head">
          <div className="bl2-tabs">
            {TABS.map((tab) => (
              <button
                key={tab.id}
                type="button"
                className={`bl2-tab${activeTab === tab.id ? " is-active" : ""}`}
                onClick={() => setActiveTab(tab.id)}
              >
                {tab.label}
                {counts[tab.id] > 0 && <span className="bl2-tab-count">{counts[tab.id]}</span>}
              </button>
            ))}
          </div>
          <span className="v2r-queue-count">{openCount} open</span>
        </div>

        <div className="bl2-kinds">
          {KINDS.map((k) => (
            <button
              key={k.id}
              type="button"
              className={`bl2-kind${kind === k.id ? " is-active" : ""}`}
              onClick={() => setKind(k.id)}
            >
              {k.label}
            </button>
          ))}
        </div>

        {loading ? (
          <div className="bl2-loading">Loading the backlog...</div>
        ) : error ? (
          <div className="bl2-error">
            Could not load the backlog. {error}
            <div><button type="button" className="bl2-retry" onClick={() => { setLoading(true); loadQueue(); }}>Retry</button></div>
          </div>
        ) : visible.length === 0 ? (
          <V2EmptyState message={
            activeTab === "new"
              ? "Nothing new to triage. Bugs and ideas from the V2 support icon land here."
              : `Nothing in ${TABS.find((t) => t.id === activeTab)?.label.toLowerCase()}.`
          } />
        ) : (
          visible.map((t) => (
            <QueueRow
              key={t.id}
              dark={dark}
              academy={clientsMap[t.client_id] || "Academy"}
              title={t.title || (KIND_LABEL[t.type] || "Request")}
              sub={subLine(t)}
              status={t.status}
              owner={t.assigned_to ? (staffMap[t.assigned_to] || "Assigned") : null}
              age={ageShort(t.updated_at || t.created_at)}
              onClick={() => setOpenId(t.id)}
            />
          ))
        )}
      </section>

      <BacklogTicketDrawer
        open={!!openTicket}
        ticket={openTicket}
        dark={dark}
        session={session}
        staffList={staffList}
        academyName={openTicket ? (clientsMap[openTicket.client_id] || "Academy") : ""}
        onClose={() => setOpenId(null)}
        onMutated={loadQueue}
      />
    </V2Page>
  );
}
